/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hrsm.UI;

import Entity.chamCong;
import com.hrsm.Utils.MsgBox;
import com.hrsm.DAO.chamCongDAO;
import com.hrsm.DAO.duAnDAO;
import com.hrsm.DAO.luongDAO;
import com.hrsm.DAO.nguoiDungDAO;
import com.hrsm.DAO.nhanVienDAO;
import com.hrsm.Entity.duAn;
import com.hrsm.Entity.luong;
import com.hrsm.Entity.nhanVien;
import com.hrsm.Utils.Auth;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class StaffJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StaffJFrame
     */
    int X, Y;

    public StaffJFrame() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnllMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbIcon_Logo = new javax.swing.JLabel();
        lbIcon_Profile = new javax.swing.JLabel();
        lbtrangThai = new javax.swing.JLabel();
        pnlMenuBar = new javax.swing.JPanel();
        pnlMenu_homPage = new javax.swing.JPanel();
        lbIcon_HomePage = new javax.swing.JLabel();
        lbName_HomaPage = new javax.swing.JLabel();
        pnlMenu_thongTin = new javax.swing.JPanel();
        lbIcon_thongTin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlMenu_duAn = new javax.swing.JPanel();
        lbIcon_duAn = new javax.swing.JLabel();
        lbName_duAn = new javax.swing.JLabel();
        pnlMenu_luong = new javax.swing.JPanel();
        lbIcon_luong = new javax.swing.JLabel();
        lbName_luong = new javax.swing.JLabel();
        pnlMenu_hoTro = new javax.swing.JPanel();
        lbIcon_hoTro = new javax.swing.JLabel();
        lbName_hoTro = new javax.swing.JLabel();
        pnlMenu_chamCong = new javax.swing.JPanel();
        lbIcon_chamCong = new javax.swing.JLabel();
        lbName_chamCong = new javax.swing.JLabel();
        pnlMenu_dangXuat = new javax.swing.JPanel();
        lbIcon_dangXuat = new javax.swing.JLabel();
        lbName_dangXuat = new javax.swing.JLabel();
        pnlMenu_thoat = new javax.swing.JPanel();
        lbIcon_thoat = new javax.swing.JLabel();
        lbName_thoat = new javax.swing.JLabel();
        pnlMenu_doiMatKhau = new javax.swing.JPanel();
        lbIcon_doiMatKhau = new javax.swing.JLabel();
        lbName_doiMatKhau = new javax.swing.JLabel();
        pnlMenu_gioiiThieu = new javax.swing.JPanel();
        lbIcon_gioithieu = new javax.swing.JLabel();
        lbName_gioiThieu = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        pnlHomePage = new javax.swing.JPanel();
        pnlHome_Header = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbName_hello = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlThongTin = new javax.swing.JPanel();
        lbIcon = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbNV_avarta = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbphongBan = new javax.swing.JLabel();
        lbngaySinh = new javax.swing.JLabel();
        lbgioiTinh = new javax.swing.JLabel();
        lbdiaChi = new javax.swing.JLabel();
        lbquocTich = new javax.swing.JLabel();
        lbcmnd = new javax.swing.JLabel();
        lbsoDT = new javax.swing.JLabel();
        lbchucDanh = new javax.swing.JLabel();
        lbloaiHinh = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        text_maNV = new javax.swing.JLabel();
        text_phongBan = new javax.swing.JLabel();
        text_ngaySinh = new javax.swing.JLabel();
        text_gioiTinh = new javax.swing.JLabel();
        text_quocTich = new javax.swing.JLabel();
        text_cmnd = new javax.swing.JLabel();
        text_sodt = new javax.swing.JLabel();
        text_chucDanh = new javax.swing.JLabel();
        text_diaChi = new javax.swing.JLabel();
        text_loaiHinh = new javax.swing.JLabel();
        text_email = new javax.swing.JLabel();
        text_tenNV = new javax.swing.JLabel();
        pnlDuAn = new javax.swing.JPanel();
        lbDA_Icon = new javax.swing.JLabel();
        lnDA_Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDA_danhSach = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cbxDA_nam = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxDA_tienDo = new javax.swing.JComboBox<>();
        pnlLuong = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblluong_danhSach = new javax.swing.JTable();
        lbluongIcon = new javax.swing.JLabel();
        lbluong_titlle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxluong_trangThai = new javax.swing.JComboBox<>();
        pnlHoTro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pnlChamCong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tabchamCong = new javax.swing.JTabbedPane();
        pnlCC_capNhat = new javax.swing.JPanel();
        lbchamCong_title = new javax.swing.JLabel();
        lbCC_maNV = new javax.swing.JLabel();
        lbCC_tenNV = new javax.swing.JLabel();
        lbCC_ngayLam = new javax.swing.JLabel();
        lbCC_thoiGian = new javax.swing.JLabel();
        lbCC_gioTangCa = new javax.swing.JLabel();
        txtCC_thoiGian = new javax.swing.JTextField();
        txtCC_maNV = new javax.swing.JTextField();
        txtCC_ngayCC = new com.toedter.calendar.JDateChooser();
        txtCC_tenNV = new javax.swing.JTextField();
        txtCC_gioTangCa = new javax.swing.JTextField();
        btnCC_chamCong = new javax.swing.JButton();
        btnCC_prev = new javax.swing.JButton();
        btnCC_next = new javax.swing.JButton();
        btnCC_last = new javax.swing.JButton();
        btnCC_first = new javax.swing.JButton();
        pnlCC_danhSach = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCC_danhSach = new javax.swing.JTable();
        pnldoiMatKhau = new javax.swing.JPanel();
        lbTitle_doiMatKhau = new javax.swing.JLabel();
        blMK_presnet = new javax.swing.JLabel();
        lbMK_new = new javax.swing.JLabel();
        lbMK_confirm = new javax.swing.JLabel();
        txtnew_pass = new javax.swing.JPasswordField();
        txtconfirm_pass = new javax.swing.JPasswordField();
        txtpresent_pass = new javax.swing.JPasswordField();
        btndoiMK_ok = new javax.swing.JButton();
        pnlgioiThieu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllMain.setBackground(new java.awt.Color(227, 233, 241));
        pnllMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_Logo.setBackground(new Color(0,0,0,0));
        lbIcon_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.jpg"))); // NOI18N
        pnlHeader.add(lbIcon_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        lbIcon_Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        pnlHeader.add(lbIcon_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 30, -1, 36));

        lbtrangThai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbtrangThai.setText("name");
        lbtrangThai.setToolTipText("");
        pnlHeader.add(lbtrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 140, 70));

        pnllMain.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, -1));

        pnlMenuBar.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu_homPage.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_homPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_homPageMouseClicked(evt);
            }
        });
        pnlMenu_homPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_HomePage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_HomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (2).png"))); // NOI18N
        pnlMenu_homPage.add(lbIcon_HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_HomaPage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_HomaPage.setText("Trang chủ");
        pnlMenu_homPage.add(lbName_HomaPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_homPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        pnlMenu_thongTin.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_thongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_thongTinMouseClicked(evt);
            }
        });
        pnlMenu_thongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_thongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_thongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        pnlMenu_thongTin.add(lbIcon_thongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Thông tin cá nhân");
        pnlMenu_thongTin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_thongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 60));

        pnlMenu_duAn.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_duAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_duAnMouseClicked(evt);
            }
        });
        pnlMenu_duAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_duAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_duAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        pnlMenu_duAn.add(lbIcon_duAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_duAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_duAn.setText("Dự án đang tiến hành");
        pnlMenu_duAn.add(lbName_duAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_duAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 60));

        pnlMenu_luong.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_luong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_luongMouseClicked(evt);
            }
        });
        pnlMenu_luong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_luong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_luong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money-bag.png"))); // NOI18N
        pnlMenu_luong.add(lbIcon_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_luong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_luong.setText("Lương");
        pnlMenu_luong.add(lbName_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 60));

        pnlMenu_hoTro.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_hoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_hoTroMouseClicked(evt);
            }
        });
        pnlMenu_hoTro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_hoTro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_hoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/headphones.png"))); // NOI18N
        pnlMenu_hoTro.add(lbIcon_hoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_hoTro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_hoTro.setText("Hỗ trợ");
        pnlMenu_hoTro.add(lbName_hoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_hoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 60));

        pnlMenu_chamCong.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_chamCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_chamCongMouseClicked(evt);
            }
        });
        pnlMenu_chamCong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_chamCong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_chamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notepad.png"))); // NOI18N
        pnlMenu_chamCong.add(lbIcon_chamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_chamCong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_chamCong.setText("Chấm công");
        pnlMenu_chamCong.add(lbName_chamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_chamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 300, 60));

        pnlMenu_dangXuat.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_dangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_dangXuatMouseClicked(evt);
            }
        });
        pnlMenu_dangXuat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_dangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-alignment.png"))); // NOI18N
        pnlMenu_dangXuat.add(lbIcon_dangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_dangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_dangXuat.setText("Đăng xuất");
        pnlMenu_dangXuat.add(lbName_dangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_dangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 60));

        pnlMenu_thoat.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_thoatMouseClicked(evt);
            }
        });
        pnlMenu_thoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_thoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_thoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel (1).png"))); // NOI18N
        pnlMenu_thoat.add(lbIcon_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_thoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_thoat.setText("Thoát");
        pnlMenu_thoat.add(lbName_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 60));

        pnlMenu_doiMatKhau.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_doiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_doiMatKhauMouseClicked(evt);
            }
        });
        pnlMenu_doiMatKhau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_doiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_doiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo-pngrepo-com.png"))); // NOI18N
        pnlMenu_doiMatKhau.add(lbIcon_doiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbName_doiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_doiMatKhau.setText("Đổi mật khẩu");
        pnlMenu_doiMatKhau.add(lbName_doiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_doiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 300, 60));

        pnlMenu_gioiiThieu.setBackground(new java.awt.Color(227, 233, 241));
        pnlMenu_gioiiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenu_gioiiThieuMouseClicked(evt);
            }
        });
        pnlMenu_gioiiThieu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon_gioithieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIcon_gioithieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        pnlMenu_gioiiThieu.add(lbIcon_gioithieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, -1));

        lbName_gioiThieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName_gioiThieu.setText("Giới thiệu & thông tin");
        pnlMenu_gioiiThieu.add(lbName_gioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        pnlMenuBar.add(pnlMenu_gioiiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 60));

        pnllMain.add(pnlMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, 730));

        pnlContainer.setBackground(new java.awt.Color(227, 233, 241));
        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabMain.setBackground(new Color(0,0,0,0));

        pnlHomePage.setBackground(new java.awt.Color(227, 233, 241));
        pnlHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome_Header.setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cut-removebg-preview.png"))); // NOI18N

        lbName_hello.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbName_hello.setForeground(new java.awt.Color(0, 0, 102));
        lbName_hello.setText("Xin chào,....");

        lbTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTime.setForeground(new java.awt.Color(0, 0, 102));
        lbTime.setText("Time...");

        javax.swing.GroupLayout pnlHome_HeaderLayout = new javax.swing.GroupLayout(pnlHome_Header);
        pnlHome_Header.setLayout(pnlHome_HeaderLayout);
        pnlHome_HeaderLayout.setHorizontalGroup(
            pnlHome_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHome_HeaderLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlHome_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName_hello)
                    .addComponent(lbTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(lbImage)
                .addGap(21, 21, 21))
        );
        pnlHome_HeaderLayout.setVerticalGroup(
            pnlHome_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHome_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
            .addGroup(pnlHome_HeaderLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lbName_hello)
                .addGap(46, 46, 46)
                .addComponent(lbTime)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlHomePage.add(pnlHome_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 1120, 420));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        pnlHomePage.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 442, 1100, 10));

        tabMain.addTab("Trang chủ", pnlHomePage);

        pnlThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        pnlThongTin.add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTitle.setText("Thông tin cá nhân");
        pnlThongTin.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, -1, 20));

        lbNV_avarta.setBackground(new java.awt.Color(204, 204, 204));
        lbNV_avarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNV_avarta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnlThongTin.add(lbNV_avarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, 360));

        lbID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbID.setText("Mã nhân viên:");
        pnlThongTin.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, 30));

        lbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTen.setText("Tên nhân viên:");
        pnlThongTin.add(lbTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 100, 30));

        lbphongBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbphongBan.setText("Phòng ban:");
        pnlThongTin.add(lbphongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 100, 30));

        lbngaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbngaySinh.setText("Ngày sinh:");
        pnlThongTin.add(lbngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, 30));

        lbgioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbgioiTinh.setText("Giới tính:");
        pnlThongTin.add(lbgioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 100, 30));

        lbdiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbdiaChi.setText("Địa chỉ:");
        pnlThongTin.add(lbdiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 100, 30));

        lbquocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbquocTich.setText("Quốc tịch:");
        pnlThongTin.add(lbquocTich, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 100, 30));

        lbcmnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbcmnd.setText("CMND/CCCD:");
        pnlThongTin.add(lbcmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 30));

        lbsoDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbsoDT.setText("Số diện thoại:");
        pnlThongTin.add(lbsoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 100, 30));

        lbchucDanh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbchucDanh.setText("Chức danh:");
        pnlThongTin.add(lbchucDanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 100, 30));

        lbloaiHinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbloaiHinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbloaiHinh.setText("Loại hình làm việc:");
        pnlThongTin.add(lbloaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 100, 30));

        lbemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbemail.setText("Email/Gnail:");
        pnlThongTin.add(lbemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 100, 30));

        text_maNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 500, 30));

        text_phongBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_phongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 500, 30));

        text_ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 500, 30));

        text_gioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 500, 30));

        text_quocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_quocTich, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 500, 30));

        text_cmnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_cmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 500, 30));

        text_sodt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_sodt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 500, 30));

        text_chucDanh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_chucDanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 500, 30));

        text_diaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 500, 30));

        text_loaiHinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_loaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 500, 30));

        text_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 500, 30));

        text_tenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlThongTin.add(text_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 500, 30));

        tabMain.addTab("Thông tin nhân viên", pnlThongTin);

        pnlDuAn.setBackground(new java.awt.Color(255, 255, 255));
        pnlDuAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDA_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        pnlDuAn.add(lbDA_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lnDA_Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnDA_Title.setText("Dự án đang tiến hành");
        pnlDuAn.add(lnDA_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tblDA_danhSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDA_danhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên phòng ban", "Tên dự án", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ));
        tblDA_danhSach.setGridColor(new java.awt.Color(204, 204, 204));
        tblDA_danhSach.setRowHeight(25);
        tblDA_danhSach.setSelectionBackground(new java.awt.Color(135, 206, 250));
        tblDA_danhSach.setShowVerticalLines(false);
        tblDA_danhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDA_danhSach);

        pnlDuAn.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1100, 620));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Năm");
        pnlDuAn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 25));

        cbxDA_nam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxDA_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDA_namActionPerformed(evt);
            }
        });
        pnlDuAn.add(cbxDA_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 480, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tiến độ");
        pnlDuAn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 25));

        cbxDA_tienDo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxDA_tienDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDA_tienDoActionPerformed(evt);
            }
        });
        pnlDuAn.add(cbxDA_tienDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 430, 25));

        tabMain.addTab("Dự án", pnlDuAn);

        pnlLuong.setBackground(new java.awt.Color(255, 255, 255));
        pnlLuong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblluong_danhSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblluong_danhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Số ngày làm", "Số ngày nghỉ", "Giờ tăng ca", "Loại vi pham", "Trách nhiệm", "Lương cơ bản", "Khấu trừ", "Thưởng", "Tổng lương", "Trạng thái"
            }
        ));
        tblluong_danhSach.setGridColor(new java.awt.Color(204, 204, 204));
        tblluong_danhSach.setRowHeight(25);
        tblluong_danhSach.setSelectionBackground(new java.awt.Color(135, 206, 250));
        tblluong_danhSach.setShowVerticalLines(false);
        tblluong_danhSach.getTableHeader().setReorderingAllowed(false);
        jScrollPane13.setViewportView(tblluong_danhSach);

        pnlLuong.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1100, 610));

        lbluongIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money-bag.png"))); // NOI18N
        pnlLuong.add(lbluongIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbluong_titlle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbluong_titlle.setText("Lương");
        pnlLuong.add(lbluong_titlle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 7, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Trạng thái");
        pnlLuong.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 30));

        cbxluong_trangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxluong_trangThai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxluong_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxluong_trangThaiActionPerformed(evt);
            }
        });
        pnlLuong.add(cbxluong_trangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 1010, 30));

        tabMain.addTab("Lương", pnlLuong);

        pnlHoTro.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoTro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/headphones.png"))); // NOI18N
        pnlHoTro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hỗ trợ");
        pnlHoTro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 14, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Liên hệ chúng tôi với:");
        pnlHoTro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telephone.png"))); // NOI18N
        pnlHoTro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("19001291");
        pnlHoTro.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Số điện thoại:");
        pnlHoTro.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        pnlHoTro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Email:");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        pnlHoTro.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Gửi câu hỏi của bạn.");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        pnlHoTro.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fax.png"))); // NOI18N
        pnlHoTro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Fax:");
        pnlHoTro.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("19001291");
        pnlHoTro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        tabMain.addTab("Hỗ trợ", pnlHoTro);

        pnlChamCong.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamCong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notepad.png"))); // NOI18N
        pnlChamCong.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Chấm công");
        pnlChamCong.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        tabchamCong.setBackground(new java.awt.Color(255, 255, 255));

        pnlCC_capNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlCC_capNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbchamCong_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbchamCong_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbchamCong_title.setText("THÔNG TIN CHẤM CÔNG");
        pnlCC_capNhat.add(lbchamCong_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1090, 40));

        lbCC_maNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCC_maNV.setText("Mã nhân viên");
        pnlCC_capNhat.add(lbCC_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lbCC_tenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCC_tenNV.setText("Tên nhân viên");
        pnlCC_capNhat.add(lbCC_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lbCC_ngayLam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCC_ngayLam.setText("Ngày chấm công");
        pnlCC_capNhat.add(lbCC_ngayLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        lbCC_thoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCC_thoiGian.setText("Thời gian làm việc");
        pnlCC_capNhat.add(lbCC_thoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lbCC_gioTangCa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCC_gioTangCa.setText("Giờ tăng ca");
        pnlCC_capNhat.add(lbCC_gioTangCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        txtCC_thoiGian.setBackground(new Color(0,0,0,0));
        txtCC_thoiGian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCC_thoiGian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCC_thoiGian.setOpaque(false);
        pnlCC_capNhat.add(txtCC_thoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 850, 30));

        txtCC_maNV.setBackground(new Color(0,0,0,0));
        txtCC_maNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCC_maNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCC_maNV.setOpaque(false);
        pnlCC_capNhat.add(txtCC_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 850, 30));

        txtCC_ngayCC.setDateFormatString("dd/MM/yyyy\t");
        pnlCC_capNhat.add(txtCC_ngayCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 850, 30));

        txtCC_tenNV.setBackground(new Color(0,0,0,0));
        txtCC_tenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCC_tenNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCC_tenNV.setOpaque(false);
        pnlCC_capNhat.add(txtCC_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 850, 30));

        txtCC_gioTangCa.setBackground(new Color(0,0,0,0));
        txtCC_gioTangCa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCC_gioTangCa.setOpaque(false);
        pnlCC_capNhat.add(txtCC_gioTangCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 850, 30));

        btnCC_chamCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCC_chamCong.setText("Chấm công");
        btnCC_chamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCC_chamCongActionPerformed(evt);
            }
        });
        pnlCC_capNhat.add(btnCC_chamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, 30));

        btnCC_prev.setText("<<");
        btnCC_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCC_prevActionPerformed(evt);
            }
        });
        pnlCC_capNhat.add(btnCC_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 60, 30));

        btnCC_next.setText(">>");
        btnCC_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCC_nextActionPerformed(evt);
            }
        });
        pnlCC_capNhat.add(btnCC_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 60, 30));

        btnCC_last.setText(">|");
        btnCC_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCC_lastActionPerformed(evt);
            }
        });
        pnlCC_capNhat.add(btnCC_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 60, 30));

        btnCC_first.setText("<|");
        btnCC_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCC_firstActionPerformed(evt);
            }
        });
        pnlCC_capNhat.add(btnCC_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 60, 30));

        tabchamCong.addTab("Cập nhật", pnlCC_capNhat);

        pnlCC_danhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblCC_danhSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblCC_danhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày chấm công", "Thời gian làm việc", "Giờ tăng ca"
            }
        ));
        tblCC_danhSach.setGridColor(new java.awt.Color(204, 204, 204));
        tblCC_danhSach.setRowHeight(25);
        tblCC_danhSach.setSelectionBackground(new java.awt.Color(135, 206, 250));
        tblCC_danhSach.setShowGrid(false);
        tblCC_danhSach.getTableHeader().setReorderingAllowed(false);
        tblCC_danhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCC_danhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCC_danhSach);

        javax.swing.GroupLayout pnlCC_danhSachLayout = new javax.swing.GroupLayout(pnlCC_danhSach);
        pnlCC_danhSach.setLayout(pnlCC_danhSachLayout);
        pnlCC_danhSachLayout.setHorizontalGroup(
            pnlCC_danhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
        );
        pnlCC_danhSachLayout.setVerticalGroup(
            pnlCC_danhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        tabchamCong.addTab("Danh sách", pnlCC_danhSach);

        pnlChamCong.add(tabchamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1100, 670));

        tabMain.addTab("Chấm công", pnlChamCong);

        pnldoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pnldoiMatKhau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle_doiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitle_doiMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        lbTitle_doiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle_doiMatKhau.setText("ĐỔI MẬT KHẨU");
        pnldoiMatKhau.add(lbTitle_doiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 1100, 30));

        blMK_presnet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        blMK_presnet.setText("Mật khẩu hiện tại");
        pnldoiMatKhau.add(blMK_presnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 30));

        lbMK_new.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMK_new.setText("Mật khẩu mới");
        pnldoiMatKhau.add(lbMK_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 30));

        lbMK_confirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMK_confirm.setText("Nhập lại mật khẩu mới");
        pnldoiMatKhau.add(lbMK_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 30));

        txtnew_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnew_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtnew_pass.setOpaque(false);
        pnldoiMatKhau.add(txtnew_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 350, 30));

        txtconfirm_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtconfirm_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtconfirm_pass.setOpaque(false);
        pnldoiMatKhau.add(txtconfirm_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 350, 30));

        txtpresent_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpresent_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtpresent_pass.setOpaque(false);
        pnldoiMatKhau.add(txtpresent_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 350, 30));

        btndoiMK_ok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndoiMK_ok.setForeground(new java.awt.Color(0, 0, 153));
        btndoiMK_ok.setText("Đồng ý");
        btndoiMK_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoiMK_okActionPerformed(evt);
            }
        });
        pnldoiMatKhau.add(btndoiMK_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, 25));

        tabMain.addTab("Đổi mật khẩu", pnldoiMatKhau);

        pnlgioiThieu.setBackground(new java.awt.Color(255, 255, 255));
        pnlgioiThieu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.jpg"))); // NOI18N
        pnlgioiThieu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 127));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setText("AIT Giải pháp CNTT và Tư vấn An ninh mạng Plc.");
        pnlgioiThieu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 580, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("AIT là một cách mới để phát triển dự án tuyệt vời tiếp theo của bạn và thuê ngoài việc phát");
        pnlgioiThieu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 580, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("triển CNTT của bạn. Từ nơi bắt đầu,");
        pnlgioiThieu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 580, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("AIT Technology đã và đang cung cấp cho khách hàng toàn bộ đội ngũ kỹ sư, nhà phát triển");
        pnlgioiThieu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 580, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("và các chuyên gia khác sẵn sàng thực hiện một dự án từ đầu đến cuối. AIT Technology đã");
        pnlgioiThieu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 580, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("triển web, Phát triển phần mềm và pps, Phát triển di động, Xây dựng thương hiệu và An");
        pnlgioiThieu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 580, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("vươn mình ra ngoài những người nội trú Châu Phi và Quốc tế , đồng thời cũng đã mở một");
        pnlgioiThieu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 580, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("nhánh tại WINDHOEK, NAMIBIA. Một loạt các dịch vụ phát triển của chúng tôi bao gồm phát");
        pnlgioiThieu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 580, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("ninh mạng.");
        pnlgioiThieu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 580, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-12-10 232640.png"))); // NOI18N
        pnlgioiThieu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 520, 740));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        pnlgioiThieu.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Giới thiệu");
        pnlgioiThieu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Còn chần chừ gì mà không nhanh tay đăng kỹ ngay vào AIT Technology của chúng tôi.");
        pnlgioiThieu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 580, -1));

        tabMain.addTab("Giới thiệu", pnlgioiThieu);

        pnlContainer.add(tabMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1120, 750));

        pnllMain.add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 1120, 730));

        getContentPane().add(pnllMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlMenu_homPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_homPageMouseClicked
        this.tabMain.setSelectedIndex(0);
    }//GEN-LAST:event_pnlMenu_homPageMouseClicked

    private void pnlMenu_thongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_thongTinMouseClicked
        this.nhanVien();
    }//GEN-LAST:event_pnlMenu_thongTinMouseClicked

    private void pnlMenu_duAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_duAnMouseClicked
        this.tabMain.setSelectedIndex(2);
    }//GEN-LAST:event_pnlMenu_duAnMouseClicked

    private void pnlMenu_luongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_luongMouseClicked
        this.luong();
    }//GEN-LAST:event_pnlMenu_luongMouseClicked

    private void pnlMenu_hoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_hoTroMouseClicked
        this.tabMain.setSelectedIndex(4);
    }//GEN-LAST:event_pnlMenu_hoTroMouseClicked

    private void pnlMenu_chamCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_chamCongMouseClicked
        this.tabMain.setSelectedIndex(5);
    }//GEN-LAST:event_pnlMenu_chamCongMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - X, y - Y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        X = evt.getX();
        Y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void pnlMenu_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_thoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlMenu_thoatMouseClicked

    private void tblCC_danhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCC_danhSachMouseClicked
        if (evt.getClickCount() == 2) {
            this.records_CC = tblCC_danhSach.getSelectedRow();
            this.CC_loadForm();
        }
    }//GEN-LAST:event_tblCC_danhSachMouseClicked

    private void btnCC_chamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCC_chamCongActionPerformed
        if (CC_validate()) {
            this.CC_insert();
        }
    }//GEN-LAST:event_btnCC_chamCongActionPerformed

    private void cbxDA_tienDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDA_tienDoActionPerformed
        this.da_fillTableInformationProject();
    }//GEN-LAST:event_cbxDA_tienDoActionPerformed

    private void cbxDA_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDA_namActionPerformed
        this.da_fillTableInformationProject();
    }//GEN-LAST:event_cbxDA_namActionPerformed

    private void pnlMenu_dangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_dangXuatMouseClicked
        this.dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_pnlMenu_dangXuatMouseClicked

    private void cbxluong_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxluong_trangThaiActionPerformed
        this.luong_fillTableSalary();
    }//GEN-LAST:event_cbxluong_trangThaiActionPerformed

    private void btnCC_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCC_firstActionPerformed
        this.CC_first();
    }//GEN-LAST:event_btnCC_firstActionPerformed

    private void btnCC_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCC_prevActionPerformed
        this.CC_prev();
    }//GEN-LAST:event_btnCC_prevActionPerformed

    private void btnCC_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCC_nextActionPerformed
        this.CC_next();
    }//GEN-LAST:event_btnCC_nextActionPerformed

    private void btnCC_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCC_lastActionPerformed
        this.CC_last();
    }//GEN-LAST:event_btnCC_lastActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        this.openGmail();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void pnlMenu_doiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_doiMatKhauMouseClicked
        this.doiMatKhau();
    }//GEN-LAST:event_pnlMenu_doiMatKhauMouseClicked

    private void btndoiMK_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoiMK_okActionPerformed
        if (MK_validate()) {
            this.getfucntionChange();
        }
    }//GEN-LAST:event_btndoiMK_okActionPerformed

    private void pnlMenu_gioiiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenu_gioiiThieuMouseClicked
        this.tabMain.setSelectedIndex(7);
    }//GEN-LAST:event_pnlMenu_gioiiThieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StaffJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blMK_presnet;
    private javax.swing.JButton btnCC_chamCong;
    private javax.swing.JButton btnCC_first;
    private javax.swing.JButton btnCC_last;
    private javax.swing.JButton btnCC_next;
    private javax.swing.JButton btnCC_prev;
    private javax.swing.JButton btndoiMK_ok;
    private javax.swing.JComboBox<String> cbxDA_nam;
    private javax.swing.JComboBox<String> cbxDA_tienDo;
    private javax.swing.JComboBox<String> cbxluong_trangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCC_gioTangCa;
    private javax.swing.JLabel lbCC_maNV;
    private javax.swing.JLabel lbCC_ngayLam;
    private javax.swing.JLabel lbCC_tenNV;
    private javax.swing.JLabel lbCC_thoiGian;
    private javax.swing.JLabel lbDA_Icon;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbIcon_HomePage;
    private javax.swing.JLabel lbIcon_Logo;
    private javax.swing.JLabel lbIcon_Profile;
    private javax.swing.JLabel lbIcon_chamCong;
    private javax.swing.JLabel lbIcon_dangXuat;
    private javax.swing.JLabel lbIcon_doiMatKhau;
    private javax.swing.JLabel lbIcon_duAn;
    private javax.swing.JLabel lbIcon_gioithieu;
    private javax.swing.JLabel lbIcon_hoTro;
    private javax.swing.JLabel lbIcon_luong;
    private javax.swing.JLabel lbIcon_thoat;
    private javax.swing.JLabel lbIcon_thongTin;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbMK_confirm;
    private javax.swing.JLabel lbMK_new;
    private javax.swing.JLabel lbNV_avarta;
    private javax.swing.JLabel lbName_HomaPage;
    private javax.swing.JLabel lbName_chamCong;
    private javax.swing.JLabel lbName_dangXuat;
    private javax.swing.JLabel lbName_doiMatKhau;
    private javax.swing.JLabel lbName_duAn;
    private javax.swing.JLabel lbName_gioiThieu;
    private javax.swing.JLabel lbName_hello;
    private javax.swing.JLabel lbName_hoTro;
    private javax.swing.JLabel lbName_luong;
    private javax.swing.JLabel lbName_thoat;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTitle_doiMatKhau;
    private javax.swing.JLabel lbchamCong_title;
    private javax.swing.JLabel lbchucDanh;
    private javax.swing.JLabel lbcmnd;
    private javax.swing.JLabel lbdiaChi;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbgioiTinh;
    private javax.swing.JLabel lbloaiHinh;
    private javax.swing.JLabel lbluongIcon;
    private javax.swing.JLabel lbluong_titlle;
    private javax.swing.JLabel lbngaySinh;
    private javax.swing.JLabel lbphongBan;
    private javax.swing.JLabel lbquocTich;
    private javax.swing.JLabel lbsoDT;
    private javax.swing.JLabel lbtrangThai;
    private javax.swing.JLabel lnDA_Title;
    private javax.swing.JPanel pnlCC_capNhat;
    private javax.swing.JPanel pnlCC_danhSach;
    private javax.swing.JPanel pnlChamCong;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlDuAn;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHoTro;
    private javax.swing.JPanel pnlHomePage;
    private javax.swing.JPanel pnlHome_Header;
    private javax.swing.JPanel pnlLuong;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlMenu_chamCong;
    private javax.swing.JPanel pnlMenu_dangXuat;
    private javax.swing.JPanel pnlMenu_doiMatKhau;
    private javax.swing.JPanel pnlMenu_duAn;
    private javax.swing.JPanel pnlMenu_gioiiThieu;
    private javax.swing.JPanel pnlMenu_hoTro;
    private javax.swing.JPanel pnlMenu_homPage;
    private javax.swing.JPanel pnlMenu_luong;
    private javax.swing.JPanel pnlMenu_thoat;
    private javax.swing.JPanel pnlMenu_thongTin;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JPanel pnldoiMatKhau;
    private javax.swing.JPanel pnlgioiThieu;
    private javax.swing.JPanel pnllMain;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTabbedPane tabchamCong;
    private javax.swing.JTable tblCC_danhSach;
    private javax.swing.JTable tblDA_danhSach;
    private javax.swing.JTable tblluong_danhSach;
    private javax.swing.JLabel text_chucDanh;
    private javax.swing.JLabel text_cmnd;
    private javax.swing.JLabel text_diaChi;
    private javax.swing.JLabel text_email;
    private javax.swing.JLabel text_gioiTinh;
    private javax.swing.JLabel text_loaiHinh;
    private javax.swing.JLabel text_maNV;
    private javax.swing.JLabel text_ngaySinh;
    private javax.swing.JLabel text_phongBan;
    private javax.swing.JLabel text_quocTich;
    private javax.swing.JLabel text_sodt;
    private javax.swing.JLabel text_tenNV;
    private javax.swing.JTextField txtCC_gioTangCa;
    private javax.swing.JTextField txtCC_maNV;
    private com.toedter.calendar.JDateChooser txtCC_ngayCC;
    private javax.swing.JTextField txtCC_tenNV;
    private javax.swing.JTextField txtCC_thoiGian;
    private javax.swing.JPasswordField txtconfirm_pass;
    private javax.swing.JPasswordField txtnew_pass;
    private javax.swing.JPasswordField txtpresent_pass;
    // End of variables declaration//GEN-END:variables

    nhanVienDAO daoNV = new nhanVienDAO();
    chamCongDAO daoCC = new chamCongDAO();
    nguoiDungDAO daoND = new nguoiDungDAO();
    luongDAO daoL = new luongDAO();
    duAnDAO daoDA = new duAnDAO();
    int records_CC = -1;

    private void init() {
        this.setLocationRelativeTo(this);
        this.getInformation();
        this.Time();
        this.CC_fillTableAttendance();
        this.da_fillComboBoxYears();
        this.da_fillComboboxProgress();
        this.da_fillTableInformationProject();
        this.luong_fillTableSalary();
        this.luong_fillComboboxProgress();

        tblCC_danhSach.setDefaultEditor(Object.class, null);
    }

    public void openGmail() {
        try {
            Desktop.getDesktop().browse(new File("src\\main\\java\\com\\hrsm\\Help\\Gmail.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }

    }

    public void getInformation() {
        try {
            String model = String.valueOf(Auth.getName());
            lbName_hello.setText("Xin chào, " + model);
            lbtrangThai.setText("Presently:   " + Auth.user);
        } catch (Exception e) {
            MsgBox.alert(this, "Chưa đăng nhập ");
        }
    }

    public void Time() {
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date now = new Date();
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat();
                    simpleDateFormat.applyPattern("hh:mm:ss aa");
                    String txt = simpleDateFormat.format(now);
                    lbTime.setText(txt);
                }
            }
        });
        t1.start();
    }

    //--------------------------------------------------------------------------
    private void nhanVien() {
        tabMain.setSelectedIndex(1);
        this.NV_informationStaff();
    }

    private void NV_informationStaff() {
        String v = String.valueOf(Auth.user);
        nhanVien nv = daoNV.selectByID(v);
        text_maNV.setText(nv.getMaNV());
        text_tenNV.setText(nv.getHoTen());
        text_phongBan.setText(nv.getTenPB());
        text_ngaySinh.setText(String.valueOf(nv.getNgaySinh()));
        text_gioiTinh.setText(nv.getGioiTinh() ? "Nam" : "Nữ");
        text_quocTich.setText(nv.getQuocTich());
        text_cmnd.setText(nv.getCMND());
        text_sodt.setText(nv.getSoDT());
        text_chucDanh.setText(nv.getChucVu() ? "Trường phòng" : "Nhân viên");
        text_loaiHinh.setText(nv.getLoaiHinh_LV());
        text_email.setText(nv.getEmail());
        text_diaChi.setText(nv.getDiaChi());
    }

    //--------------------------------Chấm công------------------------------------------
    public void CC_setForm(chamCong cc) {
        txtCC_tenNV.setText(cc.getTennv());
        txtCC_maNV.setText(cc.getManv());
        txtCC_ngayCC.setDate(cc.getNgaychamcong());
        txtCC_thoiGian.setText(String.valueOf(cc.getThoigianlam()));
        txtCC_gioTangCa.setText(String.valueOf(cc.getGiotangca()));
    }

    public void CC_fillTableAttendance() {
        DefaultTableModel model = (DefaultTableModel) tblCC_danhSach.getModel();
        model.setRowCount(0);
        try {
            String maNV = String.valueOf(Auth.user);
            List<chamCong> list = daoCC.selectByMaNV(maNV);
            for (chamCong cc : list) {
                Object[] records = {
                    cc.getManv(),
                    cc.getTennv(),
                    cc.getNgaychamcong(),
                    cc.getThoigianlam(),
                    cc.getGiotangca()
                };
                model.addRow(records);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    chamCong CC_getForm() {
        chamCong cc = new chamCong();
        cc.setManv(txtCC_maNV.getText());
        cc.setNgaychamcong(txtCC_ngayCC.getDate());
        cc.setGiotangca(Integer.parseInt(txtCC_gioTangCa.getText()));
        cc.setThoigianlam(Integer.parseInt(txtCC_thoiGian.getText()));
        return cc;
    }

    public void CC_loadForm() {
        String manv = (String) tblCC_danhSach.getValueAt(this.records_CC, 0);
        chamCong cc = daoCC.selectById(manv);
        this.CC_setForm(cc);
        tabchamCong.setSelectedIndex(0);
    }

    boolean CC_validate() {
        String v = String.valueOf(Auth.user);
        List<chamCong> list = daoCC.selectByMaNV(v);
        for (chamCong cc : list) {
            if (!cc.getManv().equalsIgnoreCase(txtCC_maNV.getText())) {
                MsgBox.alert(this, "Mã nhân viên không tồn tại");
                return false;
            } else if (cc.getNgaychamcong().equals(txtCC_ngayCC.getDate())) {
                MsgBox.alert(this, "Bạn đã chấm công vào ngày này");
                return false;
            }
        }
        return true;
    }

    public void CC_insert() {
        chamCong model = CC_getForm();
        try {
            daoCC.insert(model);
            this.CC_fillTableAttendance();
            MsgBox.alert(this, "Chấm Công Thành Công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Chấm Công Thất Bại");
        }
    }

    public void CC_first() {
        this.records_CC = 0;
        CC_edit();
    }

    public void CC_prev() {
        if (this.records_CC > 0) {
            this.records_CC--;
            CC_edit();
        } else {
            this.CC_last();
        }
    }

    public void CC_next() {
        if (this.records_CC < tblCC_danhSach.getRowCount() - 1) {
            this.records_CC++;
            CC_edit();
        } else {
            this.CC_first();
        }
    }

    public void CC_last() {
        this.records_CC = tblCC_danhSach.getRowCount() - 1;
        CC_edit();
    }

    public void CC_edit() {
        String manv = (String) tblCC_danhSach.getValueAt(this.records_CC, 0);
        chamCong kl = daoCC.selectById(manv);
        this.CC_setForm(kl);
        tabchamCong.setSelectedIndex(0);
    }

    //--------------------------------Dự án-----------------------------------------
    public void da_fillTableInformationProject() {
        DefaultTableModel model = (DefaultTableModel) tblDA_danhSach.getModel();
        model.setRowCount(0);
        try {
            String progress = (String) cbxDA_tienDo.getSelectedItem();
            String maNV = String.valueOf(Auth.user);
            int year = (Integer) cbxDA_nam.getSelectedItem();
            List<duAn> list = daoDA.selectByComponents(maNV, progress, year);
            for (duAn da : list) {
                Object[] records = {
                    da.getTenPB(),
                    da.getTenDA(),
                    da.getNgayBatDau(),
                    da.getNgayKetThuc(),
                    da.getTienDo()
                };
                model.addRow(records);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void da_fillComboBoxYears() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxDA_nam.getModel();
        model.removeAllElements();
        List<Integer> list = daoDA.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }
    }

    public void da_fillComboboxProgress() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxDA_tienDo.getModel();
        model.removeAllElements();
        List<String> list = daoDA.selectProgress();
        for (String item : list) {
            model.addElement(item);
        }
    }

    //--------------------------------Lương-----------------------------------------
    public void luong() {
        this.tabMain.setSelectedIndex(3);
    }

    public void luong_fillTableSalary() {
        DefaultTableModel model = (DefaultTableModel) tblluong_danhSach.getModel();
        model.setRowCount(0);
        String maNV = String.valueOf(Auth.user);
        String progress = (String) cbxluong_trangThai.getSelectedItem();
        List<luong> list = daoL.selectByComponents(maNV, progress);
        for (luong l : list) {
            model.addRow(new Object[]{
                l.getMaNV(),
                l.getTenNV(),
                l.getThoiGianTinh(),
                l.getSoNgayLam(),
                l.getSoNgayNghi(),
                l.getSoNgayTangCa(),
                l.getLoaiViPham(),
                l.getTrachNhiem(),
                l.getThuong(),
                l.getKhautru(),
                l.getLuongCoBan(),
                l.getTrangThai() ? "Đã xử lí" : "Đang xử lí",
                l.getTong()
            });
        }
    }

    public void luong_fillComboboxProgress() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxluong_trangThai.getModel();
        model.removeAllElements();
        List<String> list = daoL.selectProgress();
        for (String item : list) {
            model.addElement(item);
        }
    }

    //--------------------------------Đổi mật khẩu-----------------------------------------
    public void doiMatKhau() {
        tabMain.setSelectedIndex(7);
    }

    public void getfucntionChange() {
        String matKhau = new String(txtpresent_pass.getPassword());
        String matKhauMoi = new String(txtnew_pass.getPassword());
        String confirm = new String(txtconfirm_pass.getPassword());

        if (!matKhau.equals(Auth.user.getMatKhau())) {
            MsgBox.alert(this, "Sai mật khẩu!");
        } else if (!matKhauMoi.equals(confirm)) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
        } else {
            Auth.user.setMatKhau(matKhauMoi);
            daoND.update(Auth.user);
            MsgBox.alert(this, "Đổi mật khẩu thành công!");
        }
    }

    boolean MK_validate() {
        if (txtpresent_pass.getText().isEmpty() || txtnew_pass.getText().isEmpty() || txtconfirm_pass.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ dữ liệu!");
            return false;
        }
        return true;
    }
}
